### ISSUE TITLE
1. lekce - instalace - změny v zadání DÚ

### ISSUE THREAD

**Issue by dasaton** [pyladies-pilsen/pyladies-courseware#1]
V prvních dvou úkolech není jasné, co mají napsat jako řešení, takže bych volila formulaci:
1/0 - Vyzkoušejte... pokud funguje do  výsledku řešení zapište: OK
1/1 - Vyzkoušejte... pokud funguje do  výsledku řešení zapište: OK
taky u dalších by to chtělo zpřesnit, končila bych asi takto:
1/2 - Zapište správný zápis: Jak bude vypadat zápis: dělení čísla 6 číslem 3?
1/8 - Co je tady špatně? Jakým příkazem dosáhnu odpovědi: "Ahoj PyLadies!"?
1/9 - Řetězce se dají sčítat. Dají se i násobit? Dělit? Odečítat? (Odpověz slovně)   --->  Dají se u řetězců použít i operátory \*, /, -?
nebo upřesnit, jak to myslíte, protože jedna odpověď zde byla:
Násobení ano:
  print("-*"*5)  -> -*-*-*-*-*
Dělení pouze ve smyslu rozdělování řetězců na základě určitých vlastností, indexu pozice v řetězci apod.
Odečítání ne.
1/11 - úkol, co už je v 0/8 - násobení řetězců

**Comment by zitkat** [comment]
Ahoj, omlouvám se za pozdní odpověď, už jsem to opravil, podívat se můžeš tady c795f6a00605ea94e4cbad1683de1f482ea77801
